# working - Holds decoded decompressed MPE files
# new     - Holds the Full T068/168 & Upd T067/167 compressed MPE files
# ixmp    - Hold the Extracted Batch IXMPE working File

PRODUCTION :
  working :   /aci_cmm/ACI01/ICG/NETCT/files/LandingArea/Bin/wrk
  ixmp    :   /aci_cmm/ACI01/ICG/NETCT/files/LandingArea/Bin/wrk
  new     :   /aci_cmm/ACI01/ICG/NETCT/files/LandingArea/Bin
  database:   postgresql://postgres:postgres@localhost:5432/icgs
  blocks  :   70000

TEST :
  working :   data/wrk
  new     :   data/new
  ixmp    :   data
  database:   postgresql://postgres:1970Terry@localhost:5432/postgres
  blocks  :   10000

